
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";
import { dir } from 'i18next'
import { languages } from "@/app/i18n/settings";



export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children, params}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  const { lng } = params;

  return (
    <html lang={lng} dir={dir(lng)}>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
    <Header lng={lng}/>
    {children}
    </body>
    </html>
  );
}

